site_name: Документация ClinicCore

site_url: https://lilysh37.github.io/lilysh37/

repo_url: https://github.com/lilysh37/lilysh37

repo_name: GitHub Repo

theme:

  name: material # Используем современную тему Material Design

  language: ru   # Включаем русский интерфейс (поиск, кнопки)

  features:

    - navigation.expand # Раскрывающееся меню

    - content.code.copy # Кнопка копирования кода

nav:

  - Главная: index.md

  - Руководство оператора (ГОСТ 19.505):

      - Титульный лист: gost/00-title.md

      - 1. Назначение программы: gost/01-purpose.md

      - 2. Условия выполнения: gost/02-conditions.md

      - 3. Выполнение программы: gost/03-execution.md

      - 4. Сообщения оператору: gost/04-messages.md

  - Справочник разработчика:

      - API Reference: developer/api.md

plugins:

  - search

  - print-site:

      add_to_navigation: true

      print_page_title: 'Печать документации (PDF)'
